name: Dokploy deployment

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/freewill-vision/marketplace-store:latest
            ghcr.io/freewill-vision/marketplace-store:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY }}
            NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_DEFAULT_REGION=${{ vars.NEXT_PUBLIC_DEFAULT_REGION }}
            NEXT_PUBLIC_STRIPE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_KEY }}
            NEXT_PUBLIC_SITE_NAME=${{ vars.NEXT_PUBLIC_SITE_NAME }}
            NEXT_PUBLIC_SITE_DESCRIPTION=${{ vars.NEXT_PUBLIC_SITE_DESCRIPTION }}
            NEXT_PUBLIC_ALGOLIA_ID=${{ vars.NEXT_PUBLIC_ALGOLIA_ID }}
            NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}
            NEXT_PUBLIC_TALKJS_APP_ID=${{ vars.NEXT_PUBLIC_TALKJS_APP_ID }}

      - name: Get last commit info
        id: commit-info
        run: |
          # Obtener el mensaje del último commit
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -n 1)
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          
          # Obtener el hash del último commit
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Notify Dokploy
        run: |
          PAYLOAD=$(jq -n \
            --arg hash '${{ steps.commit-info.outputs.hash }}' \
            --arg message '${{ steps.commit-info.outputs.message }}' \
            --arg ref '${{ github.ref }}' \
            '{
              head_commit: {
                id: $hash,
                message: $message,
                ref: $ref
              }
            }')
          
          curl -X POST "https://dokploy.stg.freewill.vision/api/deploy/$DOKPLOY_STORE_ID" \
          -H "Content-Type: application/json" \
          -H "x-github-event: push" \
          --data "$PAYLOAD"
        env:
          DOKPLOY_STORE_ID: ${{ secrets.DOKPLOY_STORE_ID }}
